version: '3'

services:
  nextjs:
    build: ./
    ports:
      - 3005:3005 # Привязка порта 3005 контейнера к 3005 хоста
  nginx:
    build: ./nginx
    ports:
      - 8080:80 # Привязка порта 8080 хоста к 80 порту контейнера