version: '3'

services:
  recognize_app_nextjs:
    build: .
    environment:
      - NEXT_AUTH_SECRET=your_secret_key
    expose:
      - 3005 # Next.js доступен только в сети Docker
    networks:
      - recognize_app_network

  nginx:
    build: ./nginx
    depends_on:
      - recognize_app_nextjs
    ports:
      - "8080:80" # Публикация порта
    networks:
      - recognize_app_network

networks:
  recognize_app_network:
    driver: bridge
