version: '3'

services:
  nextjs:
    build: ./
    expose:
      - 3005 # Используйте expose вместо ports, чтобы контейнер был доступен только для других контейнеров в сети
  nginx:
    build: ./nginx
    ports:
      - 8080:80 # Привязка порта 8080 хоста к 80 порту контейнера